version: "3.4"
services:
  mysql:
    image: mysql:5.6
    container_name: doan_sql
    ports:
      - "9106:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: doan
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - doan_default
  phpmyadmin:
    image: phpmyadmin
    container_name: doan_phpmyadmin
    depends_on:
      - mysql
    ports:
      - "9103:80"
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - doan_default
  wp:
    depends_on:
      - mysql
    image: wordpress:5.8.3-php8.0-fpm-alpine
    container_name: doan_wp
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=doan
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=123456
      - WORDPRESS_TABLE_PREFIX=doan_
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
    restart: always
    ports:
      - "9101:9000"
    links:
      - mysql
    networks:
      - doan_default
  wp_webserver:
    restart: always
    container_name: doan_webserver
    depends_on:
      - wp
    image: nginx:1.20.2-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./html:/var/www/html
      - ./nginx/nginx_log:/var/log/nginx
    ports:
      - "9102:80"
    networks:
      - doan_default
  redis:
    image: redis:3-alpine
    container_name: doan_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/usr/local/etc/redis"
    command: redis-server --appendonly yes
  rabbitmq:
    #    image: rabbitmq
    build:
      context: .
      dockerfile: ./rabbitmq/Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: always
networks:
  doan_default:
    driver: bridge
    external: true
